services:
  postgres:
    image: postgres:15.0
    ports:
      - "5432:5432"
    environment:
      - 'POSTGRES_DB=workoutDB'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: { }
